trigger:
  branches:
    include:
    - main
    - develop
    - feature/*
    - release/v*
  tags:
    include:
      - '*'

variables:
  - name: acr_repo_suffix
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags') }}:
      value: 'prod'
    ${{ else }}:
      value: 'test'
  - group: 'ACR details'

stages:
  - stage: 'Build'
    displayName: 'Build the application'
    jobs:
      - job: 'Build'
        displayName: 'Build'
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.0'
            displayName: 'Install Node 18'
          - task: Npm@1
            inputs:
              command: 'install'
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run lint'
            displayName: 'Lint'
          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run test'
            displayName: 'Test'
          - task: Docker@2
            condition: ne(variables['Build.SourceBranchName'], 'merge')
            inputs:
              containerRegistry: 'lpgregistry ACR'
              repository: 'csl-jobs/${{ variables.acr_repo_suffix }}'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(Build.SourceBranchName)'
  - stage: 'Integration'
    displayName: 'Deploy to integration environment'
    dependsOn: 'Build'
    condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'merge'))
    jobs:
      - deployment: Deploy
        pool:
          vmImage: ubuntu-latest
        environment: integration
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionAppContainer@1
                  inputs:
                    azureSubscription: 'PrincipalConnectionStaging'
                    imageName: $(acr_url)/csl-jobs/${{ variables.acr_repo_suffix }}:$(Build.SourceBranchName)
                    appName: 'csl-jobs-integration'
