export enum JobType {
  REDUNDANT_TOKEN = 'REDUNDANT_TOKEN',
  DUPLICATE_TOKEN = 'DUPLICATE_TOKEN',
  COURSE_COMPLETIONS = 'COURSE_COMPLETIONS',
  ORG_DOMAINS = 'ORG_DOMAINS',
  OBT_STATS = 'OBT_STATS',
  SKILLS_COMPLETED_LEARNER_RECORDS = 'SKILLS_COMPLETED_LEARNER_RECORDS'
}
