services:
  ftps-server:
    build:
      context: ./ftps
      dockerfile: Dockerfile
    container_name: ftps_test_server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./ftps/data:/home/testuser
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"